language: python
before_install:
  - pip install pycodestyle
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
  - pytest --cov=solstice
  - sphinx-apidoc -f -e -o docs/sphinx solstice
  - sphinx-build -M html ./docs/sphinx ./
after_success:
  - coveralls
  - cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: hKbZ9LyfnDyFbTFEbmh3iKhsU9DuSXwJs8DRAGmBtDGpYnTmdcnLmqvDIMjVMuowSqGIa4EFJzdo9PKBt5AHcfio6N3VE5KQTVmWj8BQkJxwftLAD8AAt0aA8HesOy+ujJpyBtOiU/xdsVAAILrzwZeKMnJiDprgbPcVUbXreB9h+gQd7QNimMvpYedFhPfitm+X+Vto9shU99nBYpvm4Jr0o7sh1LjTdMiszhGFRmE44kEVY70nm1BLlE9gTzppGRyAGoGaglEzDShpCdmpN2hhYTQEYuud+Gie0dSjv2K0u45zgNGfaCfmOip7xUtEl0AnXOEqFLDJhlH7CZROmyofWEFMQSMdI+eNnJFyY83Ssi1yeFox/ZClDWxmf+HYCMnl5IHkMatl+df9/53dI5se7sJuqywxPEREMDuly7h8ij5dOx8s6YHVijLI0dIOjZ3iFN6yeesVb5ZoUNlafUQJ7N9n4bTFlW44RZENEG//klQzuOszdsV3jAlT4bYSfQjsHB1781t2IB25nwg30DNHY9n4R9WOZ4eClRMuLSjvYe8mc6ud2zKWd1NlDLraLHrwCzbyWdGrgKpELoWZvzMZxY4JbbB0KtlBazkuGe/QPLyZS4Saqvgd9qcyZcH0CBttnoImDYdNGyaJffTirbrIdC4VZkOAahzDrKya0QQ=
    on:
      branch: master
      tags: true