language: python
os: windows
install:
- pip install mkdocs
- pip install mkdocs-material
script:
- mkdocs build --config-file=solstice_docs/mkdocs.yml --verbose --clean
- move solstice_docs/site .
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site
on:
  branch: master