site_name: Solstice - Pipeline Docs
dev_addr: '127.0.0.1:9000'
sticky_navigation: False
nav:
    - Home: index.md
    - First Steps:
        - 'NDA': 'nda.md'
        - 'Shading Test': 'shadingtest.md'
    - Solstice Launcher:
      - What's Solstice Launcher?: ''
    - Solstice Pipeline:
      - Software:
        - Software Versions: solsticepipeline/software/softwareversions.md
        - Software Installation:
          - Installing Maya: solsticepipeline/software/installingmaya.md
          - Installing Arnold: solsticepipeline/software/installingarnold.md
          - Installing Yeti: solsticepipeline/software/installingyeti.md
      - Artella App:
        - What's Artella App?: solsticepipeline/artella/artellaapp.md
        - Installing Artella App: solsticepipeline/artella/installingartellaapp.md
        - Managing the Artella App: solsticepipeline/artella/managingartellaapp.md
      - Artella Pipeline:
        - Artella Nomenclature: solsticepipeline/artella/artellanomenclature.md
    - Slack: 'slack.md'
    - About: 'about.md'
theme:
  name: 'material'
  logo: 'img/solstice_avatar.png'
  feature:
    tabs: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
extra_css:
  - 'stylesheets/solstice.css'
