site_name: Solstice - Pipeline Docs
dev_addr: '127.0.0.1:9000'
sticky_navigation: False
nav:
    - Home: index.md
    - First Steps:
      - 'NDA': 'nda.md'
      - 'Shading Test': 'shadingtest.md'
    - Artella App:
      - What's Artella App?: solsticepipeline/artella/app.md
      - Installing Artella App: solsticepipeline/artella/installing.md
      - Managing the Artella App: solsticepipeline/artella/managing.md
    - Solstice Launcher:
      - What's Solstice Launcher?: solsticepipeline/solsticelauncher/app.md
      - Installing Solstice Launcher: solsticepipeline/solsticelauncher/installation.md
      - Using Solstice Launcher: solsticepipeline/solsticelauncher/usage.md
      - Uninstalling Solstice Launcher: solsticepipeline/solsticelauncher/uninstall.md
    - Solstice Pipeline:
      - Software:
        - Software Versions: solsticepipeline/software/versions.md
        - Software Installation:
          - Installing Maya: solsticepipeline/software/installingmaya.md
          - Installing Arnold: solsticepipeline/software/installingarnold.md
          - Installing Yeti: solsticepipeline/software/installingyeti.md
      - Solstice Pipeline:
        - Versions: solsticepipeline/versions.md
        - Asset: solsticepipeline/asset.md
        - Sequence: solsticepipeline/sequence.md
        - Shot: solsticepipeline/shot.md
      - Solstice Tools:
        - Solstice Tray: solsticepipeline/solsticetools/solsticetray.md
        - Solstice Shelf: solsticepipeline/solsticetools/solsticeshelf.md
        - Solstice Toolbar: solsticepipeline/solsticetools/solsticetoolbar.md
        - Solstice Changelog: solsticepipeline/solsticetools/solsticechangelog.md
        - Solstice Pipelinizer:
          - Main UI: solsticepipeline/solsticetools/pipelinizer/tool.md
          - Assets Manager: solsticepipeline/solsticetools/pipelinizer/assetmanager.md
          - Sequences Manager: solsticepipeline/solsticetools/pipelinizer/sequencesmanager.md
        - Solstice Publisher: solsticepipeline/solsticetools/solsticepublisher.md
        - Solstice Pickers: solsticepipeline/solsticetools/solsticepickers.md
      - Departments:
        - Layout:
          - Rough Layout: solsticepipeline/departments/layout/rough.md
          - Final Layout: solsticepipeline/departments/layout/final.md
        - Animation: solsticepipeline/departments/animation.md
      - FAQ:
          - How to create new working versions of an asset file?:
            - Shading Files: solsticepipeline/faq/workingversion/shading.md
            - Textures Files: solsticepipeline/faq/workingversion/textures.md
            - Model/Rig Files: solsticepipeline/faq/workingversion/model.md
          - How to publish an asset file?:
            - Shading Files: solsticepipeline/faq/publish/shading.md
            - Textures Files: solsticepipeline/faq/publish/textures.md
            - Model/Rig Files: solsticepipeline/faq/publish/model.md
    - Slack: 'slack.md'
    - About: 'about.md'
theme:
  name: 'material'
  logo: 'img/solstice_avatar.png'
  feature:
    tabs: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.tasklist
extra_css:
  - 'stylesheets/solstice.css'
